const imageUrls = [
  'https://s3.amazonaws.com/eugeniazagatphotos/clfdzqzfc0.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/slj1oezllk.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/iewp7uz5dg.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/80n5fgyy63.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/57wcegy6vf.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/bp2xgq6pxk.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/jfok8jx58n.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/u0tloup2fr.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/iaftp9hmio.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/tk17eq7bot.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/h8zjgmdpe2.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/8eoxiro4z5.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/ulwdgpe1c9.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/dc9vr741fp.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/759pqo6xpf.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/sd1rquezqg.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/c6uenyp6u0.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/f21ubl1xy0.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/lw75ndm09q.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/zfh4h5ys9h.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/myosl5h63n.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/9th1e2yle4.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/o99jmq7zif.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/s60zrdk6n5.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/5nb2exoanf.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/3wok8xzd9q.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/fcsfiuo0wr.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/3ucpp14ph6.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/6w25dmgzsj.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/4kmax4ji3a.jpg',
];

const restaurantNames = [
  'Gaggan',
  'Mejekawi',
  'Odette',
  'Jaan',
  'De Kas',
  'Metis',
  'Sisterfields',
  'Bikini Bar',
  'Den',
  'Suhring',
  'Burnt Ends',
  'Eleven Madison Park',
  'Osteria Francescana',
  'Mirazur',
  'Maido',
  'Mugaritz',
  'Arpege',
  'White Rabbit',
  'Geranium',
  'Attica',
  'Narisawa',
  'Cosme',
  'The Clove Club',
  'Arzak',
  'Tickets',
  'The Test Kitchen',
  'Florilege',
  'Mume',
  'The Chairman',
  'Carbone'];

module.exports = {
  imageUrls,
  restaurantNames,
};
