const imageUrls = [
  'https://s3.amazonaws.com/eugeniazagatphotos/1.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/2.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/3.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/4.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/5.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/6.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/7.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/8.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/9.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/10.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/11.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/12.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/13.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/14.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/15.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/16.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/17.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/18.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/19.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/20.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/21.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/22.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/23.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/24.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/25.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/26.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/27.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/28.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/29.jpg',
  'https://s3.amazonaws.com/eugeniazagatphotos/30.jpg',
];

const restaurantNames = ['Gaggan',
  'Mejekawi',
  'Odette',
  'Jaan',
  'De Kas',
  'Metis',
  'Sisterfields',
  'Bikini Bar',
  'Den',
  'Suhring',
  'Burnt Ends',
  'Eleven Madison Park',
  'Osteria Francescana',
  'Mirazur',
  'Maido',
  'Mugaritz',
  'Arpege',
  'White Rabbit',
  'Geranium',
  'Attica',
  'Narisawa',
  'Cosme',
  'The Clove Club',
  'Arzak',
  'Tickets',
  'The Test Kitchen',
  'Florilege',
  'Mume',
  'The Chairman',
  'Carbone'];

module.exports = {
  imageUrls,
  restaurantNames
};